// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shop.Models;

namespace shop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200409110849_model_changed")]
    partial class model_changed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("shop.Models.Ad", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdId");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            AdId = 1,
                            CategoryId = 0,
                            Desc = "1 room apartmant for cheap price",
                            Price = 10000,
                            SubCategoryId = 11,
                            Title = "1 room apartmant"
                        },
                        new
                        {
                            AdId = 2,
                            CategoryId = 0,
                            Desc = "2 room apartmant for cheap price",
                            Price = 20000,
                            SubCategoryId = 11,
                            Title = "2 room apartmant"
                        },
                        new
                        {
                            AdId = 3,
                            CategoryId = 0,
                            Desc = "3 room apartmant for cheap price",
                            Price = 30000,
                            SubCategoryId = 11,
                            Title = "3 room apartmant"
                        },
                        new
                        {
                            AdId = 4,
                            CategoryId = 0,
                            Desc = "small house  for cheap price",
                            Price = 50000,
                            SubCategoryId = 12,
                            Title = "small house"
                        },
                        new
                        {
                            AdId = 5,
                            CategoryId = 0,
                            Desc = "Big luxury house  for great price",
                            Price = 100000,
                            SubCategoryId = 12,
                            Title = "big house"
                        });
                });

            modelBuilder.Entity("shop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Детский мир"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Недвижимость"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Транспорт"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Запчасти для транспорта"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Работа"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Животные"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Дом и сад"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Электроника"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Бизнес и услуги"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Мода и стиль"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Хобби, отдых и спорт"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Отдам даром"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Обмен"
                        });
                });

            modelBuilder.Entity("shop.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            CategoryId = 1,
                            Name = "Детская одежда"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            CategoryId = 1,
                            Name = "Детская обувь"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            CategoryId = 1,
                            Name = "Детские коляски"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 1,
                            Name = "Детские автокресла"
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 1,
                            Name = "Детская мебель"
                        },
                        new
                        {
                            SubCategoryId = 6,
                            CategoryId = 1,
                            Name = "Игрушки"
                        },
                        new
                        {
                            SubCategoryId = 7,
                            CategoryId = 1,
                            Name = "Детский транспорт"
                        },
                        new
                        {
                            SubCategoryId = 8,
                            CategoryId = 1,
                            Name = "Товары для кормления"
                        },
                        new
                        {
                            SubCategoryId = 9,
                            CategoryId = 1,
                            Name = "Товары для школьников"
                        },
                        new
                        {
                            SubCategoryId = 10,
                            CategoryId = 1,
                            Name = "Прочие детские товары"
                        },
                        new
                        {
                            SubCategoryId = 11,
                            CategoryId = 2,
                            Name = "Квартиры, комнаты"
                        },
                        new
                        {
                            SubCategoryId = 12,
                            CategoryId = 2,
                            Name = "Дома"
                        },
                        new
                        {
                            SubCategoryId = 13,
                            CategoryId = 2,
                            Name = "Земля"
                        },
                        new
                        {
                            SubCategoryId = 14,
                            CategoryId = 2,
                            Name = "Коммерческая недвижимость"
                        },
                        new
                        {
                            SubCategoryId = 15,
                            CategoryId = 2,
                            Name = "Гаражи, парковки"
                        },
                        new
                        {
                            SubCategoryId = 16,
                            CategoryId = 2,
                            Name = "Посуточная аренда жилья"
                        },
                        new
                        {
                            SubCategoryId = 17,
                            CategoryId = 2,
                            Name = "Предложения от застройщиков"
                        },
                        new
                        {
                            SubCategoryId = 18,
                            CategoryId = 2,
                            Name = "Недвижимость за рубежом"
                        },
                        new
                        {
                            SubCategoryId = 19,
                            CategoryId = 3,
                            Name = "Легковые автомобили"
                        },
                        new
                        {
                            SubCategoryId = 20,
                            CategoryId = 3,
                            Name = "Автомобили из Польши"
                        },
                        new
                        {
                            SubCategoryId = 21,
                            CategoryId = 3,
                            Name = "Грузовые автомобили"
                        },
                        new
                        {
                            SubCategoryId = 22,
                            CategoryId = 3,
                            Name = "Автобусы "
                        },
                        new
                        {
                            SubCategoryId = 23,
                            CategoryId = 3,
                            Name = "Мото"
                        },
                        new
                        {
                            SubCategoryId = 24,
                            CategoryId = 3,
                            Name = "Спецтехника"
                        },
                        new
                        {
                            SubCategoryId = 25,
                            CategoryId = 3,
                            Name = "Сельхозтехника"
                        },
                        new
                        {
                            SubCategoryId = 26,
                            CategoryId = 3,
                            Name = "Водный транспорт "
                        },
                        new
                        {
                            SubCategoryId = 27,
                            CategoryId = 3,
                            Name = "Воздушный транспорт"
                        },
                        new
                        {
                            SubCategoryId = 28,
                            CategoryId = 3,
                            Name = "Прицепы / дома на колесах"
                        },
                        new
                        {
                            SubCategoryId = 29,
                            CategoryId = 3,
                            Name = "Другой транспорт"
                        },
                        new
                        {
                            SubCategoryId = 30,
                            CategoryId = 3,
                            Name = "Запчасти для транспорта"
                        },
                        new
                        {
                            SubCategoryId = 31,
                            CategoryId = 3,
                            Name = "Нерастаможенные автомобили"
                        },
                        new
                        {
                            SubCategoryId = 32,
                            CategoryId = 3,
                            Name = "Электромобили"
                        },
                        new
                        {
                            SubCategoryId = 33,
                            CategoryId = 4,
                            Name = "Автозапчасти и аксессуары"
                        },
                        new
                        {
                            SubCategoryId = 34,
                            CategoryId = 4,
                            Name = "Шины, диски и колёса"
                        },
                        new
                        {
                            SubCategoryId = 35,
                            CategoryId = 4,
                            Name = "Запчасти для спец / с.х. техники"
                        },
                        new
                        {
                            SubCategoryId = 36,
                            CategoryId = 4,
                            Name = "Мотозапчасти и аксессуары"
                        },
                        new
                        {
                            SubCategoryId = 37,
                            CategoryId = 4,
                            Name = "Прочие запчасти"
                        },
                        new
                        {
                            SubCategoryId = 38,
                            CategoryId = 4,
                            Name = "Транспорт"
                        },
                        new
                        {
                            SubCategoryId = 39,
                            CategoryId = 5,
                            Name = "Розничная торговля / продажи / закупки"
                        },
                        new
                        {
                            SubCategoryId = 40,
                            CategoryId = 5,
                            Name = "Транспорт / логистика"
                        },
                        new
                        {
                            SubCategoryId = 41,
                            CategoryId = 5,
                            Name = "Строительство"
                        },
                        new
                        {
                            SubCategoryId = 42,
                            CategoryId = 5,
                            Name = "Телекоммуникации / связь"
                        },
                        new
                        {
                            SubCategoryId = 43,
                            CategoryId = 5,
                            Name = "Бары / рестораны"
                        },
                        new
                        {
                            SubCategoryId = 44,
                            CategoryId = 5,
                            Name = "Юриспруденция и бухгалтерия"
                        },
                        new
                        {
                            SubCategoryId = 45,
                            CategoryId = 5,
                            Name = "Управление персоналом / HR"
                        },
                        new
                        {
                            SubCategoryId = 46,
                            CategoryId = 5,
                            Name = "Охрана / безопасность"
                        },
                        new
                        {
                            SubCategoryId = 47,
                            CategoryId = 5,
                            Name = "Домашний персонал"
                        },
                        new
                        {
                            SubCategoryId = 48,
                            CategoryId = 5,
                            Name = "Красота / фитнес / спорт"
                        },
                        new
                        {
                            SubCategoryId = 49,
                            CategoryId = 5,
                            Name = "Туризм / отдых / развлечения"
                        },
                        new
                        {
                            SubCategoryId = 50,
                            CategoryId = 5,
                            Name = "Образование"
                        },
                        new
                        {
                            SubCategoryId = 51,
                            CategoryId = 5,
                            Name = "Культура / искусство"
                        },
                        new
                        {
                            SubCategoryId = 52,
                            CategoryId = 5,
                            Name = "Медицина / фармация"
                        },
                        new
                        {
                            SubCategoryId = 53,
                            CategoryId = 5,
                            Name = "ИТ / телеком / компьютеры"
                        },
                        new
                        {
                            SubCategoryId = 54,
                            CategoryId = 5,
                            Name = "Банки / финансы / страхование"
                        },
                        new
                        {
                            SubCategoryId = 55,
                            CategoryId = 5,
                            Name = "Недвижимость"
                        },
                        new
                        {
                            SubCategoryId = 56,
                            CategoryId = 5,
                            Name = "Маркетинг / реклама / дизайн"
                        },
                        new
                        {
                            SubCategoryId = 57,
                            CategoryId = 5,
                            Name = "Производство / энергетика"
                        },
                        new
                        {
                            SubCategoryId = 58,
                            CategoryId = 5,
                            Name = "Сельское хозяйство / агробизнес / лесное хозяйство"
                        },
                        new
                        {
                            SubCategoryId = 59,
                            CategoryId = 5,
                            Name = "Cекретариат / АХО"
                        },
                        new
                        {
                            SubCategoryId = 60,
                            CategoryId = 5,
                            Name = "Частичная занятость"
                        },
                        new
                        {
                            SubCategoryId = 61,
                            CategoryId = 5,
                            Name = "Начало карьеры / Студенты"
                        },
                        new
                        {
                            SubCategoryId = 62,
                            CategoryId = 5,
                            Name = "Сервис и быт"
                        },
                        new
                        {
                            SubCategoryId = 63,
                            CategoryId = 5,
                            Name = "Другие сферы занятий"
                        },
                        new
                        {
                            SubCategoryId = 64,
                            CategoryId = 5,
                            Name = "Работа за рубежом"
                        },
                        new
                        {
                            SubCategoryId = 65,
                            CategoryId = 6,
                            Name = "Бесплатно (животные и вязка)"
                        },
                        new
                        {
                            SubCategoryId = 66,
                            CategoryId = 6,
                            Name = "Собаки"
                        },
                        new
                        {
                            SubCategoryId = 67,
                            CategoryId = 6,
                            Name = "Кошки"
                        },
                        new
                        {
                            SubCategoryId = 68,
                            CategoryId = 6,
                            Name = "Аквариумистика"
                        },
                        new
                        {
                            SubCategoryId = 69,
                            CategoryId = 6,
                            Name = "Птицы"
                        },
                        new
                        {
                            SubCategoryId = 70,
                            CategoryId = 6,
                            Name = "Грызуны"
                        },
                        new
                        {
                            SubCategoryId = 71,
                            CategoryId = 6,
                            Name = "Рептилии"
                        },
                        new
                        {
                            SubCategoryId = 72,
                            CategoryId = 6,
                            Name = "Сельхоз животные"
                        },
                        new
                        {
                            SubCategoryId = 73,
                            CategoryId = 6,
                            Name = "Другие  животные"
                        },
                        new
                        {
                            SubCategoryId = 74,
                            CategoryId = 6,
                            Name = "Зоотовары"
                        },
                        new
                        {
                            SubCategoryId = 75,
                            CategoryId = 6,
                            Name = "Вязка"
                        },
                        new
                        {
                            SubCategoryId = 76,
                            CategoryId = 6,
                            Name = "Бюро находок"
                        },
                        new
                        {
                            SubCategoryId = 77,
                            CategoryId = 7,
                            Name = "Канцтовары / расходные материалы"
                        },
                        new
                        {
                            SubCategoryId = 78,
                            CategoryId = 7,
                            Name = "Мебель"
                        },
                        new
                        {
                            SubCategoryId = 79,
                            CategoryId = 7,
                            Name = "Продукты питания / напитки"
                        },
                        new
                        {
                            SubCategoryId = 80,
                            CategoryId = 7,
                            Name = "Сад / огород"
                        },
                        new
                        {
                            SubCategoryId = 81,
                            CategoryId = 7,
                            Name = "Предметы интерьера"
                        },
                        new
                        {
                            SubCategoryId = 82,
                            CategoryId = 7,
                            Name = "Строительство / ремонт"
                        },
                        new
                        {
                            SubCategoryId = 83,
                            CategoryId = 7,
                            Name = "Инструменты"
                        },
                        new
                        {
                            SubCategoryId = 84,
                            CategoryId = 7,
                            Name = "Комнатные растения"
                        },
                        new
                        {
                            SubCategoryId = 85,
                            CategoryId = 7,
                            Name = "Посуда / кухонная утварь"
                        },
                        new
                        {
                            SubCategoryId = 86,
                            CategoryId = 7,
                            Name = "Садовый инвентарь"
                        },
                        new
                        {
                            SubCategoryId = 87,
                            CategoryId = 7,
                            Name = "Хозяйственный инвентарь / бытовая химия"
                        },
                        new
                        {
                            SubCategoryId = 88,
                            CategoryId = 7,
                            Name = "Прочие товары для дома"
                        },
                        new
                        {
                            SubCategoryId = 89,
                            CategoryId = 8,
                            Name = "Телефоны и аксессуары"
                        },
                        new
                        {
                            SubCategoryId = 90,
                            CategoryId = 8,
                            Name = "Компьютеры и комплектующие"
                        },
                        new
                        {
                            SubCategoryId = 91,
                            CategoryId = 8,
                            Name = "Фото / видео"
                        },
                        new
                        {
                            SubCategoryId = 92,
                            CategoryId = 8,
                            Name = "Тв / видеотехника"
                        },
                        new
                        {
                            SubCategoryId = 93,
                            CategoryId = 8,
                            Name = "Аудиотехника"
                        },
                        new
                        {
                            SubCategoryId = 94,
                            CategoryId = 8,
                            Name = "Игры и игровые приставки"
                        },
                        new
                        {
                            SubCategoryId = 95,
                            CategoryId = 8,
                            Name = "Планшеты / эл. книги и аксессуары"
                        },
                        new
                        {
                            SubCategoryId = 96,
                            CategoryId = 8,
                            Name = "Ноутбуки и аксессуары"
                        },
                        new
                        {
                            SubCategoryId = 97,
                            CategoryId = 8,
                            Name = "Техника для дома"
                        },
                        new
                        {
                            SubCategoryId = 98,
                            CategoryId = 8,
                            Name = "Техника для кухни"
                        },
                        new
                        {
                            SubCategoryId = 99,
                            CategoryId = 8,
                            Name = "Климатическое оборудование"
                        },
                        new
                        {
                            SubCategoryId = 100,
                            CategoryId = 8,
                            Name = "Индивидуальный уход"
                        },
                        new
                        {
                            SubCategoryId = 101,
                            CategoryId = 8,
                            Name = "Аксессуары и комплектующие"
                        },
                        new
                        {
                            SubCategoryId = 102,
                            CategoryId = 8,
                            Name = "Прочая электроника"
                        },
                        new
                        {
                            SubCategoryId = 103,
                            CategoryId = 8,
                            Name = "Ремонт и обслуживание техники"
                        },
                        new
                        {
                            SubCategoryId = 104,
                            CategoryId = 9,
                            Name = "Строительство / ремонт / уборка"
                        },
                        new
                        {
                            SubCategoryId = 105,
                            CategoryId = 9,
                            Name = "Финансовые услуги / партнерство"
                        },
                        new
                        {
                            SubCategoryId = 106,
                            CategoryId = 9,
                            Name = "Перевозки / аренда транспорта"
                        },
                        new
                        {
                            SubCategoryId = 107,
                            CategoryId = 9,
                            Name = "Реклама / полиграфия / маркетинг / интернет"
                        },
                        new
                        {
                            SubCategoryId = 108,
                            CategoryId = 9,
                            Name = "Няни / сиделки"
                        },
                        new
                        {
                            SubCategoryId = 109,
                            CategoryId = 9,
                            Name = "Сырьё / материалы"
                        },
                        new
                        {
                            SubCategoryId = 110,
                            CategoryId = 9,
                            Name = "Красота / здоровье"
                        },
                        new
                        {
                            SubCategoryId = 111,
                            CategoryId = 9,
                            Name = "Оборудование"
                        },
                        new
                        {
                            SubCategoryId = 112,
                            CategoryId = 9,
                            Name = "Образование / Спорт"
                        },
                        new
                        {
                            SubCategoryId = 113,
                            CategoryId = 9,
                            Name = "Услуги для животных"
                        },
                        new
                        {
                            SubCategoryId = 114,
                            CategoryId = 9,
                            Name = "Продажа бизнеса"
                        },
                        new
                        {
                            SubCategoryId = 115,
                            CategoryId = 9,
                            Name = "Развлечения / Искусство / Фото / Видео"
                        },
                        new
                        {
                            SubCategoryId = 116,
                            CategoryId = 9,
                            Name = "Туризм / иммиграция"
                        },
                        new
                        {
                            SubCategoryId = 117,
                            CategoryId = 9,
                            Name = "Услуги переводчиков / набор текста"
                        },
                        new
                        {
                            SubCategoryId = 118,
                            CategoryId = 9,
                            Name = "Авто / мото услуги"
                        },
                        new
                        {
                            SubCategoryId = 119,
                            CategoryId = 9,
                            Name = "Ремонт и обслуживание техники"
                        },
                        new
                        {
                            SubCategoryId = 120,
                            CategoryId = 9,
                            Name = "Сетевой маркетинг"
                        },
                        new
                        {
                            SubCategoryId = 121,
                            CategoryId = 9,
                            Name = "Юридические услуги"
                        },
                        new
                        {
                            SubCategoryId = 122,
                            CategoryId = 9,
                            Name = "Прокат товаров"
                        },
                        new
                        {
                            SubCategoryId = 123,
                            CategoryId = 9,
                            Name = "Прочие услуги"
                        },
                        new
                        {
                            SubCategoryId = 124,
                            CategoryId = 10,
                            Name = "Одежда/обувь"
                        },
                        new
                        {
                            SubCategoryId = 125,
                            CategoryId = 10,
                            Name = "Для свадьбы"
                        },
                        new
                        {
                            SubCategoryId = 126,
                            CategoryId = 10,
                            Name = "Наручные часы"
                        },
                        new
                        {
                            SubCategoryId = 127,
                            CategoryId = 10,
                            Name = "Аксессуары"
                        },
                        new
                        {
                            SubCategoryId = 128,
                            CategoryId = 10,
                            Name = "Подарки"
                        },
                        new
                        {
                            SubCategoryId = 129,
                            CategoryId = 10,
                            Name = "Красота / здоровье"
                        },
                        new
                        {
                            SubCategoryId = 130,
                            CategoryId = 10,
                            Name = "Мода разное"
                        },
                        new
                        {
                            SubCategoryId = 131,
                            CategoryId = 11,
                            Name = "Антиквариат / коллекции"
                        },
                        new
                        {
                            SubCategoryId = 132,
                            CategoryId = 11,
                            Name = "Музыкальные инструменты"
                        },
                        new
                        {
                            SubCategoryId = 133,
                            CategoryId = 11,
                            Name = "Спорт / отдых"
                        },
                        new
                        {
                            SubCategoryId = 134,
                            CategoryId = 11,
                            Name = "Книги / журналы"
                        },
                        new
                        {
                            SubCategoryId = 135,
                            CategoryId = 11,
                            Name = "CD / DVD / пластинки / кассеты"
                        },
                        new
                        {
                            SubCategoryId = 136,
                            CategoryId = 11,
                            Name = "Билеты"
                        },
                        new
                        {
                            SubCategoryId = 137,
                            CategoryId = 11,
                            Name = "Поиск попутчиков"
                        },
                        new
                        {
                            SubCategoryId = 138,
                            CategoryId = 11,
                            Name = "Поиск групп / музыкантов"
                        },
                        new
                        {
                            SubCategoryId = 139,
                            CategoryId = 11,
                            Name = "Другое"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
